version: '3.8'
services:
  blogging_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogging
    volumes:
      - db_data:/var/lib/mysql

  blogging_app:
    image: bloggingwebsite-app
    depends_on:
      - blogging_db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://blogging_db:3306/blogging
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  db_data:
